### PR TITLE
Bump pullapprove to v2, now starring danbills!

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1: thanks for doing this, I know at least wdltool needs similar love.

[Approved with PullApprove](https://pullapprove.com/broadinstitute/lenthall/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/lenthall)

**Comment by kshakir** [comment]
Checked in wdltool [current](https://github.com/broadinstitute/wdltool/blob/154f98619d445b025a16ae3ca2e01ec6ccc1d9a9/.pullapprove.yml) develop-- he's all set!

**Comment by mcovarr** [comment]
@kshakir oh sweet I guess the PR I was on just needs a rebase

**Comment by danbills** [comment]
💯

**Comment by Horneth** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/lenthall/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/lenthall)

**Pull request merged**
