### PR TITLE
Upgrade to scala 2.12

### PR DESCRIPTION
**Pull request by geoffjentry**
- Remove Spray code
- Update build.sbt to allow for cross version builds
- Update publish scripts to publish multiple versions to artifactory

### CODE REVIEW

**Comment by geoffjentry** [comment]
The publish scripts work when I run them locally but will need to verify once merged

**Comment by kshakir** [comment]
Re: testing publish scripts non-locally, to test publish even before a PR I'll often push a commit with a change to [publish_snapshot.sh](https://github.com/broadinstitute/lenthall/blob/fdd7e59852dddeeed910ca06d4e58db14c7aaff2/src/bin/publish_snapshot.sh#L9) that changes the conditional to something like:

```bash
if [ "$TRAVIS_BRANCH" == "ks_my_test_branch" ] || [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
```

And for other future readers, one should have the artifactory credentials and clean out the test artifacts.

**Comment by kshakir** [comment]
👍 

Also [pinging](https://github.com/broadinstitute/cromwell/pull/2093) the cromwell PR.

**Comment by Horneth** [comment]
👍

**Pull request merged**
