### PR TITLE
Add configOption function

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by cjllanwarne** [comment]
This looks really good :+1:

**Comment by geoffjentry** [comment]
@Horneth Is there any reason to not merge this?

**Comment by Horneth** [comment]
Nop, I just completely forgot about it -_-

**Comment by geoffjentry** [comment]
@Horneth This function also exists in WorkflowDescriptor in cromwell. Can you remove it from there and switch to using that one? It has a "TODO: add to lenthall" or something like that as well :)

**Comment by Horneth** [comment]
Sure :)

**Pull request merged**
